# Generated by Django 6.0.4 on 2026-04-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=11)),
                ('razon_social', models.CharField(max_length=255)),
                ('nombre_comercial', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('departamento', models.CharField(default='AREQUIPA', max_length=50)),
                ('provincia', models.CharField(default='AREQUIPA', max_length=50)),
                ('distrito', models.CharField(default='AREQUIPA', max_length=50)),
                ('usuario_sol', models.CharField(default='MODDATOS', max_length=50)),
                ('clave_sol', models.CharField(default='MODDATOS', max_length=50)),
                ('certificado_digital', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('password_certificado', models.CharField(blank=True, max_length=100, null=True)),
                ('ambiente', models.CharField(choices=[('BETA', 'Pruebas (BETA)'), ('PRODUCCION', 'Producción')], default='BETA', max_length=20)),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuración de Empresa',
            },
        ),
    ]
