# Generated by Django 6.0.4 on 2026-05-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_cliente_activo_producto_activo_proveedor_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='persona_contacto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
