# Generated by Django 6.0.4 on 2026-05-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_proveedor_persona_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='persona_contacto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
