# Generated by Django 6.0.4 on 2026-05-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_cliente_persona_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('TURISMO', 'Servicio Turístico'), ('HOSPEDAJE', 'Hospedaje'), ('SOUVENIR', 'Souvenir / Producto'), ('RESTAURANTE', 'Restaurante'), ('OTROS', 'Otros')], default='SOUVENIR', max_length=20),
        ),
    ]
