# Generated by Django 6.0.4 on 2026-05-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='modulo',
            field=models.CharField(choices=[('HOTEL', 'Hotel'), ('RESTAURANTE', 'Restaurante')], default='HOTEL', max_length=20),
        ),
        migrations.AddField(
            model_name='compra',
            name='modulo',
            field=models.CharField(choices=[('HOTEL', 'Hotel'), ('RESTAURANTE', 'Restaurante')], default='HOTEL', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='modulo',
            field=models.CharField(choices=[('HOTEL', 'Hotel'), ('RESTAURANTE', 'Restaurante')], default='HOTEL', max_length=20),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='modulo',
            field=models.CharField(choices=[('HOTEL', 'Hotel'), ('RESTAURANTE', 'Restaurante')], default='HOTEL', max_length=20),
        ),
        migrations.AddField(
            model_name='registroservicio',
            name='modulo',
            field=models.CharField(choices=[('HOTEL', 'Hotel'), ('RESTAURANTE', 'Restaurante')], default='HOTEL', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='modulo',
            field=models.CharField(choices=[('HOTEL', 'Hotel'), ('RESTAURANTE', 'Restaurante')], default='HOTEL', max_length=20),
        ),
    ]
