# Generated by Django 6.0.4 on 2026-05-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_habitacion_reserva_pedidohabitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='habitaciones/'),
        ),
    ]
