# Generated by Django 6.0.4 on 2026-05-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_habitacion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
