# Generated by Django 6.0.4 on 2026-05-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_habitacion_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
