# Generated by Django 6.0.4 on 2026-05-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_reserva_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='tipo_comprobante',
            field=models.CharField(choices=[('BOLETA', 'Boleta'), ('FACTURA', 'Factura'), ('TICKET', 'Ticket'), ('OTRO', 'Otro')], default='FACTURA', max_length=50),
        ),
    ]
