# Generated by Django 6.0.4 on 2026-05-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_compra_forma_pago_compra_num_cuotas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
