# Generated by Django 6.0.4 on 2026-05-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_compra_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='impuesto',
            field=models.CharField(choices=[('IGV', 'IGV (18%)'), ('EXONERADO', 'Exonerado'), ('INAFECTO', 'Inafecto')], default='IGV', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_alerta',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_ideal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
