# Generated by Django 6.0.4 on 2026-05-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_producto_impuesto_producto_stock_alerta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_corporativo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Corporativo'),
        ),
    ]
