# Generated by Django 6.0.4 on 2026-05-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_producto_precio_corporativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='precio_noche_corporativo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
