# Generated by Django 6.0.4 on 2026-05-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_habitacion_precio_noche_corporativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresa/logos/'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='nombre_sistema',
            field=models.CharField(default='TurismoERP', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='ruta_referencia',
            field=models.CharField(blank=True, help_text='Ruta local de instalación o backups', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='tipo_impresion',
            field=models.CharField(choices=[('A4', 'Impresora Estándar (A4)'), ('TICKET', 'Ticketera (80mm)')], default='A4', max_length=10),
        ),
    ]
