# Generated by Django 6.0.4 on 2026-05-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_configuracionempresa_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='forma_logo',
            field=models.CharField(choices=[('RECTANGULAR', 'Rectangular / Original'), ('CIRCULAR', 'Circular (Avatar)')], default='RECTANGULAR', max_length=20),
        ),
    ]
