# Generated by Django 6.0.4 on 2026-05-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_configuracionempresa_forma_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('capacidad', models.PositiveIntegerField(default=4)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('RESERVADA', 'Reservada'), ('LIMPIEZA', 'En Limpieza')], default='DISPONIBLE', max_length=20)),
                ('posicion_x', models.IntegerField(default=0, help_text='Para el mapa visual')),
                ('posicion_y', models.IntegerField(default=0, help_text='Para el mapa visual')),
            ],
        ),
    ]
