# Generated by Django 6.0.4 on 2026-05-14 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='es_comanda',
            field=models.BooleanField(default=False, help_text='Si es True, es un pedido abierto en mesa'),
        ),
        migrations.AddField(
            model_name='venta',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.mesa'),
        ),
    ]
