# Generated by Django 6.0.4 on 2026-05-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('ENTRADA', 'Entrada'), ('PLATO_FONDO', 'Plato de Fondo'), ('POSTRE', 'Postre'), ('BEBIDA', 'Bebida'), ('LICOR', 'Licor / Trago'), ('OTRO', 'Otro')], default='OTRO', max_length=100, null=True),
        ),
    ]
