# Generated by Django 6.0.4 on 2026-05-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0023_alter_producto_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='formato_hotel',
            field=models.CharField(choices=[('A4', 'Impresora Estándar (A4)'), ('TICKET_80', 'Ticketera Térmica (80mm)'), ('TICKET_58', 'Ticketera Térmica (58mm)')], default='A4', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='formato_restaurante',
            field=models.CharField(choices=[('A4', 'Impresora Estándar (A4)'), ('TICKET_80', 'Ticketera Térmica (80mm)'), ('TICKET_58', 'Ticketera Térmica (58mm)')], default='TICKET_80', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='imprimir_logo_ticket',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='mensaje_pie_pagina',
            field=models.TextField(blank=True, help_text='Mensaje al final de los tickets', null=True),
        ),
        migrations.AlterField(
            model_name='configuracionempresa',
            name='tipo_impresion',
            field=models.CharField(choices=[('A4', 'Impresora Estándar (A4)'), ('TICKET_80', 'Ticketera Térmica (80mm)'), ('TICKET_58', 'Ticketera Térmica (58mm)')], default='A4', max_length=20),
        ),
    ]
