# Generated by Django 6.0.4 on 2026-05-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_configuracionempresa_formato_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='nombre_impresora_hotel',
            field=models.CharField(blank=True, help_text='Nombre de la impresora en Windows para el Hotel', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='nombre_impresora_restaurante',
            field=models.CharField(blank=True, help_text='Nombre de la impresora en Windows para el Restaurante', max_length=100, null=True),
        ),
    ]
