# Generated by Django 6.0.4 on 2026-05-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0025_configuracionempresa_nombre_impresora_hotel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('modulo', models.CharField(default='RESTAURANTE', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pedidohabitacion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='subcategoria',
            field=models.CharField(blank=True, default='OTRO', max_length=100, null=True),
        ),
    ]
