# Generated by Django 6.0.4 on 2026-05-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0027_detalleventa_mozo_detalleventa_silla_estadocomanda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='subestado_limpieza',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDO', 'Recibido'), ('LIMPIANDO', 'En Limpieza'), ('TERMINADO', 'Terminado')], default='PENDIENTE', max_length=20),
        ),
    ]
