# Generated by Django 6.0.4 on 2026-05-20 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0028_habitacion_subestado_limpieza'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='personal_limpieza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habitaciones_limpieza', to=settings.AUTH_USER_MODEL),
        ),
    ]
