# Generated by Django 6.0.4 on 2026-05-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0029_habitacion_personal_limpieza'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='codigo_grupo',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Código de Grupo'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='condicion_pago',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Condición de Pago'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_desayuno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hora Desayuno'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='n_pax',
            field=models.PositiveIntegerField(default=1, verbose_name='N° PAX'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='placa_vehiculo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Placa / Otros'),
        ),
    ]
