# Generated by Django 6.0.4 on 2026-06-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0031_alter_habitacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='izipay_comision_porcentaje',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=5, verbose_name='Comisión Izipay (%)'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='incluido_tour',
            field=models.BooleanField(default=False, verbose_name='Incluido con el Tour'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Petición especial o detalles del cliente', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Comisión del Plato'),
        ),
        migrations.AddField(
            model_name='venta',
            name='encargado_guia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Guía / Encargado'),
        ),
        migrations.AddField(
            model_name='venta',
            name='pago_tarjeta',
            field=models.BooleanField(default=False, verbose_name='Pago con Tarjeta'),
        ),
        migrations.AddField(
            model_name='venta',
            name='recargo_tarjeta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Recargo Tarjeta (5%)'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('MOZO', 'Mozo'), ('JEFE_MOZO', 'Jefe de Mozos'), ('COCINA', 'Cocina'), ('BARRA', 'Barra'), ('LIMPIEZA', 'Limpieza')], default='ADMIN', max_length=20),
        ),
    ]
